### ISSUE TITLE
Why is there a rate limit of 99.99?

### ISSUE THREAD

**Issue by logan-jobzmall** [cybercog/laravel-love#190]
Hi,

This is just an architectural question. We wanted to try to add more to the rate depending on the user, but noticed it is capped at 99.99. What was the idea behind this cap? Thanks for the information.

Logan

**Comment by antonkomarev** [comment]
Here is a link on [Reaction System v2 design process](https://github.com/cybercog/laravel-love/issues/85)

Reaction type has mass. It multiplies on reaction rate to receive weight of the reaction. I decided to limit this value because in [v3 system](https://github.com/cybercog/laravel-love/discussions/153) it will be multiplied on reaction force and then we might have too big numbers in final values. We need to to store aggregated counters in database, and if these values will be too big - we might need to switch from bigint to varchar column.
