### ISSUE TITLE
How to stop queue-ing new jobs

### ISSUE THREAD

**Issue by m7vm7v** [cybercog/laravel-love#209]
First of all great package, many thanks for the support!

Is there a way not to use the laravel's queueable jobs but calculate the count on a go?

Or if we do not use the count feature, can we stop filling the jobs table?

**Comment by antonkomarev** [comment]
Yes, you can disable counters aggregating, but this way is not suggested because you have to implement all on-the-fly logic by yourself and it will be pretty complex and slightly increase load.

You can use [opt-out package discovery](https://laravel.com/docs/9.x/packages#opting-out-of-package-discovery) in composer.json of your app.

```json
"extra": {
    "laravel": {
        "dont-discover": [
            "cybercog/laravel-love"
        ]
    }
},
```

This will disable auto-discovery of 2 service providers:
- `Cog\Laravel\Love\LoveServiceProvider`
- `Cog\Laravel\Love\LoveEventServiceProvider`

Then you have to register `Cog\Laravel\Love\LoveServiceProvider` manually in `config/app.php` file, because it contains core functionality.
