### ISSUE TITLE
 Specific Columns in likesCounter returns null

### ISSUE THREAD

**Issue by corvuss** [cybercog/laravel-love#33]
This:
 ->with('likesCounter')
return 
"likes_counter": {
                "id": 1,
                "likeable_type": "App\\Company",
                "likeable_id": 1,
                "type_id": "LIKE",
                "count": 1,
                "created_at": "2018-07-07 19:28:53",
                "updated_at": "2018-08-09 03:49:40"
            }
And this
 ->with('likesCounter:count')
return
"likes_counter": null

**Comment by antonkomarev** [comment]
Maybe you need to declare column using dot?
```
->with('likesCounter.count')
```

**Comment by antonkomarev** [comment]
Ah... sorry, my mistake, you had right syntax. Need to check it.

**Comment by antonkomarev** [comment]
Confirming that this issue exists. I think that this issue hidden in framework. Because if you will add `likeable_id` column - you will get the records. But I'm afraid it might require `likeable_type` to resolve what type of records to fetch and maybe `type_id` to resolve what type do you need.

In short, this will work, but maybe it will have issues with correct data:
```php
->with('likesCounter:count,likeable_id')
```
Then you could try:
```php
->with('likesCounter:count,likeable_type,likeable_id,type_id')
```
We should investigate it more and open issue in laravel/framework repository with provided failing tests. I'm closing this issue since it's couldn't be solved on package level. Feel free to continue conversation if you'll find more information.
