### ISSUE TITLE
in a nutshell what are the reasons for the huge changes between v5 and v6?

### ISSUE THREAD

**Issue by vesper8** [cybercog/laravel-love#60]
Just wondering because I'm now using V5 and it's working perfectly fine for me. Is V6 more versatile somehow? Does it allow for more stats? More flexibility? Or is it just a cleaner refactoring that doesn't really add benefits to the end-user?

In my application I only have users "liking" other users.. as simple a use-case as possible I imagine. I like to stay up to date with packages but I'd like to know what I'll gain if anything from doing this upgrade.

Many thanks!

**Comment by antonkomarev** [comment]
Initially this package was a simple implementation of likes system ([Laravel Likeable](https://github.com/cybercog/laravel-likeable)) and there are a lot of alternatives for it. Later I decided to completely revise architecture of my packages and Laravel Love became a pilot version.

## In short

If Laravel Love v5 was enough for you - there is no reason to upgrade to v6 in near future. It's completely another architectural approach which adds much more possibilities to extension, maintenance & scalability.

## Explanation

There are many reasons why I decided to make such a big changes.

### Application was tightly coupled with package

#### Old architecture

Package was aware of application's `User` model, it could work with `User` model only. In an opposite - application `User` model was aware how to like, dislike, unlike, undislike other models and check if models were liked or disliked. And `Likeable` models were aware how to do a lot of things too. There was issue that when `User` is `Liker` and `Likeable` in a same time - you cannot clearly say what `likes` method should return: likes which user was made or likes which user was received.

#### New architecture

It was pretty hard to start thinking in this way, but User model shouldn't know how to do any kind of job in application subsystems. It should be connected to another class which will be responsible to it. All functionality implemented in `Reacter` & `Reactant` models. Package don't care if `Reacterable` & `Reactable` models exists at all. It opens possibility to extract package data to microservice with smaller efforts.

### Reaction types limitations

#### Old architecture

It was limited to `like` & `dislike` reactions. To add new reaction type you were needed to add a lot of methods which are duplicate each other.

#### New architecture

You are free to add any amount of reaction types in no time, name them as you want and enhance them with application specific features. There is no need to change code base to add new reaction types.

### Database consistency & performance

#### Old architecture

There was no way to add foreign keys to database because Likeable model was represented as 2 columns in `likes` table.

#### New architecture

There is no composite keys anymore and we can easily link database records with each other without any issues. Initially I've thought that such complex architecture have significant performance issues, but in fact when indexes were placed, eager loaded added to all requests - queries started to execute even faster.

**Comment by antonkomarev** [comment]
I'm closing this issue. Feel free to continue the conversation here if there are more questions.
