### ISSUE TITLE
Refactor package relations

### ISSUE THREAD

**Issue by antonkomarev** [cybercog/laravel-love#7]
I decided to revise and extend relationships in v6. Initially was planned to do it in v5 but it will require database changes and Laravel 5.6 `morphTo` implementation.

There is a need to fetch:

1. Likeables of the Liker.
2. Likers of the Likeable.
3. (?) Likes which were added to Likeables.
4. (?) Likes which were added by Liker.

*I'm not 100% sure about points 3 & 4. Do we really need to get those likes? Need to write use cases for them.*

#### Old implementation

Only 3rd point is implemented right now.

```php
// Likes and dislikes related to Likeable
$likesAndDislikes = $article->likesAndDislikes();

// Likes related to Likeable
$likes = $article->likes();

// Dislikes related to Likeable
$dislikes = $article->dislikes();
```

**Comment by a-komarev** [comment]
##### Option №1

`Likeable` model relationships leave without changes.

`Liker` model will have relationships `likedAndDisliked`, `liked`, `disliked` which returns likes they created.

```php
// Likeables liked or disliked by user
$likeables = $user->likedAndDisliked();

// Likeables liked by user
$likedLikables = $user->liked();

// Likeables disliked by user
$dislikedLikeables = $user->disliked();
```

***Drawback:** There is no clear understanding that it's `HasMany` relationship. Name should be plural.*
***Drawback:** Can not get Like id, because `Likeable` entities will be returned instead of `Like`.*

##### Option №2

`Likeable` model relationships leave without changes.

`Liker` model will have relationships `likeables`, `likedLikeables`, `dislikedLikeables` which returns likes they created.

```php
// Likeables liked or disliked by user
$likedAndDisliked = $user->likeables();

// Likeables liked by user
$liked = $user->likedLikeables();

// Likeables disliked by user
$disliked = $user->dislikedLikeables();
```

***Drawback:** Can not get Like id, because `Likeable` entities will be returned instead of `Like`.*

##### Option №3

`Likeable` model relationships `likesAndDislikes`, `likes`, `dislikes` should be removed to `likersAndDislikers`, `likers`, `dislikers` to let `Likeable` models act as `Likers`.

```php
// Likers who liked or disliked Likeable
$likersAndDislikers = $article->likersAndDislikers();

// Likers who liked Likeable
$likers = $article->likers();

// Likers who disliked Likeable
$dislikers = $article->dislikers();
```
***TODO:** We need to decide what this relationships should return `Like` or `Likers` models collection.*
***Drawback:** There is no clear understanding that `Like` models will be returned, could lead to misunderstandings.*

`Liker` model will have relationships `likesAndDislikes`, `likes`, `dislikes` which returns likes they created.

```php
// Likes and dislikes created by user
$dislikes = $user->likesAndDislikes();

// Likes created by user
$likes = $user->likes();

// Dislikes created by user
$dislikes = $user->dislikes();
```

**Comment by a-komarev** [comment]
##### Option №2

`Likeable` model relationships leave without changes.

`Liker` model will have relationships `likeables`, `likedLikeables`, `dislikedLikeables` which returns likes they created.

```php
// Likeables liked or disliked by user
$likedAndDisliked = $user->likeables();

// Likeables liked by user
$liked = $user->likedLikeables();

// Likeables disliked by user
$disliked = $user->dislikedLikeables();
```

***Drawback:** Can not get Like id, because `Likeable` entities will be returned instead of `Like`.*

##### Option №3

`Likeable` model relationships `likesAndDislikes`, `likes`, `dislikes` should be removed to `likersAndDislikers`, `likers`, `dislikers` to let `Likeable` models act as `Likers`.

```php
// Likers who liked or disliked Likeable
$likersAndDislikers = $article->likersAndDislikers();

// Likers who liked Likeable
$likers = $article->likers();

// Likers who disliked Likeable
$dislikers = $article->dislikers();
```
***TODO:** We need to decide what this relationships should return `Like` or `Likers` models collection.*
***Drawback:** There is no clear understanding that `Like` models will be returned, could lead to misunderstandings.*

`Liker` model will have relationships `likesAndDislikes`, `likes`, `dislikes` which returns likes they created.

```php
// Likes and dislikes created by user
$dislikes = $user->likesAndDislikes();

// Likes created by user
$likes = $user->likes();

// Dislikes created by user
$dislikes = $user->dislikes();
```

**Comment by a-komarev** [comment]
##### Option №3

`Likeable` model relationships `likesAndDislikes`, `likes`, `dislikes` should be removed to `likersAndDislikers`, `likers`, `dislikers` to let `Likeable` models act as `Likers`.

```php
// Likers who liked or disliked Likeable
$likersAndDislikers = $article->likersAndDislikers();

// Likers who liked Likeable
$likers = $article->likers();

// Likers who disliked Likeable
$dislikers = $article->dislikers();
```
***TODO:** We need to decide what this relationships should return `Like` or `Likers` models collection.*
***Drawback:** There is no clear understanding that `Like` models will be returned, could lead to misunderstandings.*

`Liker` model will have relationships `likesAndDislikes`, `likes`, `dislikes` which returns likes they created.

```php
// Likes and dislikes created by user
$dislikes = $user->likesAndDislikes();

// Likes created by user
$likes = $user->likes();

// Dislikes created by user
$dislikes = $user->dislikes();
```

**Comment by a-komarev** [comment]
### 2. Likers of the Likeable

##### Option №2

`Likeable` model will have new relationships `likersAndDislikers`, `likers`, `dislikers` to let `Likeable` models act as `Likers`.

```php
// Likers who liked or disliked Likeable
$likersAndDislikers = $article->likersAndDislikers();

// Likers who liked Likeable
$likers = $article->likers();

// Likers who disliked Likeable
$dislikers = $article->dislikers();
```
***TODO:** We need to decide what this relationships should return `Like` or `Likers` models collection.*
***Drawback:** There is no clear understanding that `Like` models will be returned, could lead to misunderstandings.*

**Comment by a-komarev** [comment]
### 2. Likers of the Likeable

##### Option №3

`Likeable` model will have new relationships `likers`, `likersLiked`, `likersDisliked` to let `Likeable` models act as `Liker` too.

```php
// Likers who liked or disliked Likeable
$likersAndDislikers = $article->likers();

// Likers who liked Likeable
$likers = $article->likersLiked();

// Likers who disliked Likeable
$dislikers = $article->likersDisliked();
```

**Drawback:** It looks like it should return boolean value.

**Comment by a-komarev** [comment]
`Liker` model will have relationships `likesAndDislikes`, `likes`, `dislikes` which returns likes they created.

```php
// Likes and dislikes created by user
$dislikes = $user->likesAndDislikes();

// Likes created by user
$likes = $user->likes();

// Dislikes created by user
$dislikes = $user->dislikes();
```

**Comment by a-komarev** [comment]
```php
// Likes and dislikes which were added to Likeable
$dislikes = $articles->likedLikesAndDislikes();

// Likes which were added to Likeable
$likes = $article->likedLikes();

// Dislikes which were added to Likeable
$dislikes = $article->likedDislikes();
```

**Comment by a-komarev** [comment]
```php
// Likes and dislikes which were added to Likeable
$dislikes = $articles->likesAndDislikes();

// Likes which were added to Likeable
$likes = $article->likes();

// Dislikes which were added to Likeable
$dislikes = $article->dislikes();
```

**Comment by antonkomarev** [comment]
Closing this issue since its outdated. I've completely revised an API of the next package version.
More details about v6: https://github.com/cybercog/laravel-love/issues/15
